i386_dev_DIR=$(PWD)/arch/i386/dev
INCLUDE+=-I$(i386_dev_DIR)/include
obj-y+=$(i386_dev_DIR)/dma.o
obj-$(CONFIG_FLOPPY)+=$(i386_dev_DIR)/floppy.o
obj-$(CONFIG_BCON)+=$(i386_dev_DIR)/bcon.o
obj-$(CONFIG_KBD)+=$(i386_dev_DIR)/kbd.o
