dev_DIR=$(PWD)/dev
INCLUDE+=-I$(dev_DIR)/include
obj-$(CONFIG_KBD)+=$(dev_DIR)/kbd.o
obj-$(CONFIG_BCON)+=$(dev_DIR)/bcon.o
obj-$(CONFIG_BCON)+=$(dev_DIR)/bcon_kbd.o
obj-$(CONFIG_BCON)+=$(dev_DIR)/bcon_cursor.o
